In [1]:
""" # Install required library (run once)
! pip install datasets pandas -q """

from datasets import load_dataset
import pandas as pd
import json
import os
folder_name = "Cleaned_chatdoctor_dataset"
os.makedirs(folder_name, exist_ok=True)
# Load dataset
dataset = load_dataset("lavita/ChatDoctor-HealthCareMagic-100k")
# Convert to pandas
df = dataset["train"].to_pandas()
# Convert directly to JSON file (fast)
df.to_json("chatdocter_Cleaned_data.json", orient="records", indent=4)
print("JSON file saved successfully!")
print(df.head())

c:\Users\santo\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Generating train split: 100%|██████████| 112165/112165 [00:00<00:00, 222161.93 examples/s]

JSON file saved successfully!
                                         instruction  \
0  If you are a doctor, please answer the medical...
1  If you are a doctor, please answer the medical...
2  If you are a doctor, please answer the medical...
3  If you are a doctor, please answer the medical...
4  If you are a doctor, please answer the medical...

                                               input  \
0  I woke up this morning feeling the whole room ...
1  My baby has been pooing 5-6 times a day for a ...
2  Hello, My husband is taking Oxycodone due to a...
3  lump under left nipple and stomach pain (male)...
4  I have a 5 month old baby who is very congeste...

                                              output
0  Hi, Thank you for posting your query. The most...
1  Hi... Thank you for consulting in Chat Doctor....
2  Hello, and I hope I can help you today.First, ...
3  HI. You have two different problems. The lump ...
4  Thank you for using Chat Doctor. I would sugge...

In [2]:
# Convert train split into pandas dataframe
df = dataset["train"].to_pandas()

# Show first 5 rows
df.head()

,instruction,input,output
0,"If you are a doctor, please answer the medical...",I woke up this morning feeling the whole room ...,"Hi, Thank you for posting your query. The most..."
1,"If you are a doctor, please answer the medical...",My baby has been pooing 5-6 times a day for a ...,Hi... Thank you for consulting in Chat Doctor....
2,"If you are a doctor, please answer the medical...","Hello, My husband is taking Oxycodone due to a...","Hello, and I hope I can help you today.First, ..."
3,"If you are a doctor, please answer the medical...",lump under left nipple and stomach pain (male)...,HI. You have two different problems. The lump ...
4,"If you are a doctor, please answer the medical...",I have a 5 month old baby who is very congeste...,Thank you for using Chat Doctor. I would sugge...

In [4]:
df = pd.read_json(r"D:\Santosh D\Study\College\Projects\SHIP\chatdocter_Cleaned_data.json")

In [12]:
df

,instruction,input,output
0,"If you are a doctor, please answer the medical...",I woke up this morning feeling the whole room ...,"Hi, Thank you for posting your query. The most..."
1,"If you are a doctor, please answer the medical...",My baby has been pooing 5-6 times a day for a ...,Hi... Thank you for consulting in Chat Doctor....
2,"If you are a doctor, please answer the medical...","Hello, My husband is taking Oxycodone due to a...","Hello, and I hope I can help you today.First, ..."
3,"If you are a doctor, please answer the medical...",lump under left nipple and stomach pain (male)...,HI. You have two different problems. The lump ...
4,"If you are a doctor, please answer the medical...",I have a 5 month old baby who is very congeste...,Thank you for using Chat Doctor. I would sugge...
...,...,...,...
112160,"If you are a doctor, please answer the medical...",im 25 years old ..i started using mtp kit on 5...,"Hello, Thanks for letting us know your health ..."
112161,"If you are a doctor, please answer the medical...",My 5 year old son has been coughing for a mont...,As you have mentioned in your history that you...
112162,"If you are a doctor, please answer the medical...",My toes on right foot more than left are numb ...,Hi. The numbness and blue discoloration could ...
112163,"If you are a doctor, please answer the medical...","I was diagnosis with pleurisy last Tuesday, an...",Thanks for your question on Chat Doctor. Treat...
112164,"If you are a doctor, please answer the medical...","Within the past few hours, my husband has deve...","Hello, Thank you for posting on Chat Doctor. T..."

CONVERT INTO CSV_FILE

In [5]:
from datasets import load_dataset
import pandas as pd
# Fast load from Hugging Face
dataset = load_dataset("lavita/ChatDoctor-HealthCareMagic-100k")
# Convert directly to pandas DataFrame (fast)
df = dataset["train"].to_pandas()

# Save CSV
df.to_csv("Cleaned_Chatdocter_dataset.csv", index=False)

print("CSV saved successfully!")
print("Shape:", df.shape)
print(df.head())

CSV saved successfully!
Shape: (112165, 3)
                                         instruction  \
0  If you are a doctor, please answer the medical...
1  If you are a doctor, please answer the medical...
2  If you are a doctor, please answer the medical...
3  If you are a doctor, please answer the medical...
4  If you are a doctor, please answer the medical...

                                               input  \
0  I woke up this morning feeling the whole room ...
1  My baby has been pooing 5-6 times a day for a ...
2  Hello, My husband is taking Oxycodone due to a...
3  lump under left nipple and stomach pain (male)...
4  I have a 5 month old baby who is very congeste...

                                              output
0  Hi, Thank you for posting your query. The most...
1  Hi... Thank you for consulting in Chat Doctor....
2  Hello, and I hope I can help you today.First, ...
3  HI. You have two different problems. The lump ...
4  Thank you for using Chat Doctor. I would sugge...

In [6]:
import os
print(os.getcwd())

d:\Santosh D\Study\College\Projects\SHIP

In [8]:
df = pd.read_csv(r"D:\Santosh D\Study\College\Projects\SHIP\Cleaned_Chatdocter_dataset.csv")

In [15]:
df

,instruction,input,output
0,"If you are a doctor, please answer the medical...",I woke up this morning feeling the whole room ...,"Hi, Thank you for posting your query. The most..."
1,"If you are a doctor, please answer the medical...",My baby has been pooing 5-6 times a day for a ...,Hi... Thank you for consulting in Chat Doctor....
2,"If you are a doctor, please answer the medical...","Hello, My husband is taking Oxycodone due to a...","Hello, and I hope I can help you today.First, ..."
3,"If you are a doctor, please answer the medical...",lump under left nipple and stomach pain (male)...,HI. You have two different problems. The lump ...
4,"If you are a doctor, please answer the medical...",I have a 5 month old baby who is very congeste...,Thank you for using Chat Doctor. I would sugge...
...,...,...,...
112160,"If you are a doctor, please answer the medical...",im 25 years old ..i started using mtp kit on 5...,"Hello, Thanks for letting us know your health ..."
112161,"If you are a doctor, please answer the medical...",My 5 year old son has been coughing for a mont...,As you have mentioned in your history that you...
112162,"If you are a doctor, please answer the medical...",My toes on right foot more than left are numb ...,Hi. The numbness and blue discoloration could ...
112163,"If you are a doctor, please answer the medical...","I was diagnosis with pleurisy last Tuesday, an...",Thanks for your question on Chat Doctor. Treat...
112164,"If you are a doctor, please answer the medical...","Within the past few hours, my husband has deve...","Hello, Thank you for posting on Chat Doctor. T..."